### PR TITLE
CT-108: Setup drone

### PR DESCRIPTION
**Pull request by tylerlevine**

### CODE REVIEW

**Comment by tylerlevine** [comment]
Will need to have drone configured by ops for this PR to have any effect.

See OPS-1673.

**Comment by Xekyo** [comment]
Waiting for Drone to be deployed before merging.

**Comment by tylerlevine** [comment]
Drone is set up and seems to be working well. Branch protection rules were also updated.

I think this is ready to land, further adjustments can be made later if necessary.

**Comment by Xekyo** [comment]
Thanks for the walkthrough. LGTM, please add yourself as a code owner with us as well for the drone related files.

**Pull request merged**
