### PR TITLE
Remove Mark from Codeowners

### PR DESCRIPTION
**Pull request by Xekyo**
Ticket: BG-23797

### CODE REVIEW

**Review by OttoAllmendinger — DISMISSED** [review]
CI failures unrelated

**Comment by Xekyo** [comment]
Just FYI, I can't merge anymore since I'm not a member of the BitGo organization.

**Comment by OttoAllmendinger** [comment]
@paddyquinn looks like you need to approve as well

**Review by paddyquinn — APPROVED** [review]

**Comment by paddyquinn** [comment]
I approved as well but it doesn't look like that's the issue. It looks like the commit is not signed, which disallows merging. I'll take over the PR, sign the commit and then hopefully we can merge it.

**Review by paddyquinn — APPROVED** [review]

**Comment by Xekyo** [comment]
I think it was signed, but then I removed `mark@bitgo.com` from my GPG key. :)

Thanks!

**Pull request merged**
